/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package apacheThriftSrvB;

import java.util.Map;

public class MensajeInServicioNoThrift {
  public Map<String,String> cabecera; // required
  public Map<String,String> cuerpo; // required

  public MensajeInServicioNoThrift() {
  }

  public MensajeInServicioNoThrift(
    Map<String,String> cabecera,
    Map<String,String> cuerpo)
  {
    this();
    this.cabecera = cabecera;
    this.cuerpo = cuerpo;
  }

  public Map<String,String> getCabecera() {
    return this.cabecera;
  }

  public MensajeInServicioNoThrift setCabecera(Map<String,String> cabecera) {
    this.cabecera = cabecera;
    return this;
  }

  public Map<String,String> getCuerpo() {
    return this.cuerpo;
  }

  public MensajeInServicioNoThrift setCuerpo(Map<String,String> cuerpo) {
    this.cuerpo = cuerpo;
    return this;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MensajeInServicio(");
    boolean first = true;

    sb.append("cabecera:");
    if (this.cabecera == null) {
      sb.append("null");
    } else {
      sb.append(this.cabecera);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cuerpo:");
    if (this.cuerpo == null) {
      sb.append("null");
    } else {
      sb.append(this.cuerpo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

}

