/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package apacheThriftSrvB;

import java.util.List;
import java.util.Map;

public class MensajeOutServicioNoThrift {
  public Map<String,String> cabecera; // required
  public Map<String,List<PrendaNoThrift>> cuerpo; // required
  public String aviso; // required

  public MensajeOutServicioNoThrift() {
  }

  public MensajeOutServicioNoThrift(
    Map<String,String> cabecera,
    Map<String,List<PrendaNoThrift>> cuerpo,
    String aviso)
  {
    this();
    this.cabecera = cabecera;
    this.cuerpo = cuerpo;
    this.aviso = aviso;
  }

  public Map<String,String> getCabecera() {
    return this.cabecera;
  }

  public MensajeOutServicioNoThrift setCabecera(Map<String,String> cabecera) {
    this.cabecera = cabecera;
    return this;
  }

  public Map<String,List<PrendaNoThrift>> getCuerpo() {
    return this.cuerpo;
  }

  public MensajeOutServicioNoThrift setCuerpo(Map<String,List<PrendaNoThrift>> cuerpo) {
    this.cuerpo = cuerpo;
    return this;
  }

  public String getAviso() {
    return this.aviso;
  }

  public MensajeOutServicioNoThrift setAviso(String aviso) {
    this.aviso = aviso;
    return this;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MensajeOutServicio(");
    boolean first = true;

    sb.append("cabecera:");
    if (this.cabecera == null) {
      sb.append("null");
    } else {
      sb.append(this.cabecera);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cuerpo:");
    if (this.cuerpo == null) {
      sb.append("null");
    } else {
      sb.append(this.cuerpo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("aviso:");
    if (this.aviso == null) {
      sb.append("null");
    } else {
      sb.append(this.aviso);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

}

